defmodule BlogWeb.VerifiedRoutes do
  @moduledoc """
  Provides compile-time verified routes for BlogWeb.

  This module is automatically generated by Phoenix 1.7+ and provides
  the ~p sigil for route generation with compile-time verification.
  """
  use Phoenix.VerifiedRoutes,
    endpoint: BlogWeb.Endpoint,
    router: BlogWeb.Router,
    statics: BlogWeb.static_paths()
end
